# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ShopiHI"
client_id = "1783a21f9b5b8e9a68d4ea140422d760"
application_url = "https://amongst-declaration-level-big.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://amongst-declaration-level-big.trycloudflare.com/auth/callback",
  "https://amongst-declaration-level-big.trycloudflare.com/auth/shopify/callback",
  "https://amongst-declaration-level-big.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "heitzsystem.myshopify.com"
